-- ============================================================
-- SEED: Catálogo de material de osteosíntesis (510 SKUs)
-- ============================================================

BEGIN;

INSERT INTO public.catalogo_material (nombre, sistema, tipo, diametro_mm, orificios, longitud_mm, variante) VALUES
('Placa DCP 4.5mm angosta 5 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 5, NULL, NULL),
('Placa DCP 4.5mm angosta 6 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 6, NULL, NULL),
('Placa DCP 4.5mm angosta 7 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 7, NULL, NULL),
('Placa DCP 4.5mm angosta 8 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 8, NULL, NULL),
('Placa DCP 4.5mm angosta 9 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 9, NULL, NULL),
('Placa DCP 4.5mm angosta 10 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 10, NULL, NULL),
('Placa DCP 4.5mm angosta 12 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 12, NULL, NULL),
('Placa DCP 4.5mm ancha 6 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 6, NULL, NULL),
('Placa DCP 4.5mm ancha 8 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 8, NULL, NULL),
('Placa DCP 4.5mm ancha 10 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 10, NULL, NULL),
('Placa DCP 4.5mm ancha 12 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 12, NULL, NULL),
('Placa DCP 4.5mm ancha 14 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 14, NULL, NULL),
('Placa LC-DCP 4.5mm angosta 5 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 5, NULL, NULL),
('Placa LC-DCP 4.5mm angosta 6 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 6, NULL, NULL),
('Placa LC-DCP 4.5mm angosta 7 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 7, NULL, NULL),
('Placa LC-DCP 4.5mm angosta 8 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 8, NULL, NULL),
('Placa LC-DCP 4.5mm angosta 9 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 9, NULL, NULL),
('Placa LC-DCP 4.5mm angosta 10 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 10, NULL, NULL),
('Placa LC-DCP 4.5mm angosta 12 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 12, NULL, NULL),
('Placa LC-DCP 4.5mm ancha 6 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 6, NULL, NULL),
('Placa LC-DCP 4.5mm ancha 8 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 8, NULL, NULL),
('Placa LC-DCP 4.5mm ancha 10 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 10, NULL, NULL),
('Placa LC-DCP 4.5mm ancha 12 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 12, NULL, NULL),
('Placa LC-DCP 4.5mm ancha 14 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 14, NULL, NULL),
('Placa LCP 4.5mm angosta 5 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 5, NULL, NULL),
('Placa LCP 4.5mm angosta 6 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 6, NULL, NULL),
('Placa LCP 4.5mm angosta 7 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 7, NULL, NULL),
('Placa LCP 4.5mm angosta 8 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 8, NULL, NULL),
('Placa LCP 4.5mm angosta 9 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 9, NULL, NULL),
('Placa LCP 4.5mm angosta 10 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 10, NULL, NULL),
('Placa LCP 4.5mm angosta 12 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 12, NULL, NULL),
('Placa LCP 4.5mm angosta 14 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 14, NULL, NULL),
('Placa LCP 4.5mm ancha 6 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 6, NULL, NULL),
('Placa LCP 4.5mm ancha 8 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 8, NULL, NULL),
('Placa LCP 4.5mm ancha 10 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 10, NULL, NULL),
('Placa LCP 4.5mm ancha 12 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 12, NULL, NULL),
('Placa LCP 4.5mm ancha 14 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 14, NULL, NULL),
('Placa de reconstrucción 4.5mm 6 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 6, NULL, NULL),
('Placa de reconstrucción 4.5mm 8 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 8, NULL, NULL),
('Placa de reconstrucción 4.5mm 10 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 10, NULL, NULL),
('Placa de reconstrucción 4.5mm 12 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 12, NULL, NULL),
('Placa de reconstrucción 4.5mm 14 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 14, NULL, NULL),
('Placa de reconstrucción 4.5mm 16 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 16, NULL, NULL),
('Placa de reconstrucción 4.5mm bloqueada 6 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 6, NULL, NULL),
('Placa de reconstrucción 4.5mm bloqueada 8 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 8, NULL, NULL),
('Placa de reconstrucción 4.5mm bloqueada 10 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 10, NULL, NULL),
('Placa de reconstrucción 4.5mm bloqueada 12 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 12, NULL, NULL),
('Placa de reconstrucción 4.5mm bloqueada 14 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 14, NULL, NULL),
('Placa de reconstrucción 4.5mm bloqueada 16 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 16, NULL, NULL),
('Placa en T 4.5mm 4 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 4, NULL, NULL),
('Placa en T 4.5mm 5 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 5, NULL, NULL),
('Placa en T 4.5mm 6 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 6, NULL, NULL),
('Placa en T 4.5mm 7 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 7, NULL, NULL),
('Placa en T 4.5mm 8 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 8, NULL, NULL),
('Placa en L 4.5mm 4 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 4, NULL, NULL),
('Placa en L 4.5mm 5 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 5, NULL, NULL),
('Placa en L 4.5mm 6 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 6, NULL, NULL),
('Placa en L 4.5mm 7 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 7, NULL, NULL),
('Placa en L 4.5mm 8 orificios', 'Grandes Fragmentos', 'Placa', 4.5, 8, NULL, NULL),
('Placa DHS 2 orificios', 'Grandes Fragmentos', 'Placa', NULL, 2, NULL, 'ángulo 135°'),
('Placa DHS 3 orificios', 'Grandes Fragmentos', 'Placa', NULL, 3, NULL, 'ángulo 135°'),
('Placa DHS 4 orificios', 'Grandes Fragmentos', 'Placa', NULL, 4, NULL, 'ángulo 135°'),
('Placa DHS 5 orificios', 'Grandes Fragmentos', 'Placa', NULL, 5, NULL, 'ángulo 135°'),
('Placa DHS 6 orificios', 'Grandes Fragmentos', 'Placa', NULL, 6, NULL, 'ángulo 135°'),
('Placa DHS 8 orificios', 'Grandes Fragmentos', 'Placa', NULL, 8, NULL, 'ángulo 135°'),
('Placa DHS 10 orificios', 'Grandes Fragmentos', 'Placa', NULL, 10, NULL, 'ángulo 135°'),
('Placa DHS 12 orificios', 'Grandes Fragmentos', 'Placa', NULL, 12, NULL, 'ángulo 135°'),
('Placa DCS 4 orificios', 'Grandes Fragmentos', 'Placa', NULL, 4, NULL, 'ángulo 95°'),
('Placa DCS 6 orificios', 'Grandes Fragmentos', 'Placa', NULL, 6, NULL, 'ángulo 95°'),
('Placa DCS 8 orificios', 'Grandes Fragmentos', 'Placa', NULL, 8, NULL, 'ángulo 95°'),
('Placa DCS 10 orificios', 'Grandes Fragmentos', 'Placa', NULL, 10, NULL, 'ángulo 95°'),
('Placa DCS 12 orificios', 'Grandes Fragmentos', 'Placa', NULL, 12, NULL, 'ángulo 95°'),
('Placa anatómica de húmero proximal PHILOS 3 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 3, NULL, 'húmero proximal'),
('Placa anatómica de húmero proximal PHILOS 5 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 5, NULL, 'húmero proximal'),
('Placa anatómica de húmero proximal PHILOS 8 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 8, NULL, 'húmero proximal'),
('Placa anatómica de húmero distal medial 8 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 8, NULL, 'húmero distal medial'),
('Placa anatómica de húmero distal medial 12 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 12, NULL, 'húmero distal medial'),
('Placa anatómica de húmero distal medial 16 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 16, NULL, 'húmero distal medial'),
('Placa anatómica de húmero distal lateral 6 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 6, NULL, 'húmero distal lateral'),
('Placa anatómica de húmero distal lateral 8 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 8, NULL, 'húmero distal lateral'),
('Placa anatómica de húmero distal lateral 12 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 12, NULL, 'húmero distal lateral'),
('Placa anatómica de fémur distal lateral 5 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 5, NULL, 'fémur distal'),
('Placa anatómica de fémur distal lateral 7 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 7, NULL, 'fémur distal'),
('Placa anatómica de fémur distal lateral 9 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 9, NULL, 'fémur distal'),
('Placa anatómica de fémur distal lateral 11 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 11, NULL, 'fémur distal'),
('Placa anatómica de fémur distal lateral 13 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 13, NULL, 'fémur distal'),
('Placa anatómica de fémur proximal LCP-PF 4 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 4, NULL, 'fémur proximal'),
('Placa anatómica de fémur proximal LCP-PF 6 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 6, NULL, 'fémur proximal'),
('Placa anatómica de fémur proximal LCP-PF 8 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 8, NULL, 'fémur proximal'),
('Placa anatómica de fémur proximal LCP-PF 10 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 10, NULL, 'fémur proximal'),
('Placa anatómica de tibia proximal lateral 4 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 4, NULL, 'tibia proximal lateral'),
('Placa anatómica de tibia proximal lateral 6 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 6, NULL, 'tibia proximal lateral'),
('Placa anatómica de tibia proximal lateral 8 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 8, NULL, 'tibia proximal lateral'),
('Placa anatómica de tibia proximal lateral 10 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 10, NULL, 'tibia proximal lateral'),
('Placa anatómica de tibia proximal lateral 12 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 12, NULL, 'tibia proximal lateral'),
('Placa anatómica de tibia proximal lateral 14 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 14, NULL, 'tibia proximal lateral'),
('Placa anatómica de tibia proximal medial 4 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 4, NULL, 'tibia proximal medial'),
('Placa anatómica de tibia proximal medial 6 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 6, NULL, 'tibia proximal medial'),
('Placa anatómica de tibia proximal medial 8 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 8, NULL, 'tibia proximal medial'),
('Placa anatómica de tibia distal medial 4 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 4, NULL, 'tibia distal medial'),
('Placa anatómica de tibia distal medial 6 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 6, NULL, 'tibia distal medial'),
('Placa anatómica de tibia distal medial 8 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 8, NULL, 'tibia distal medial'),
('Placa anatómica de tibia distal medial 10 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 10, NULL, 'tibia distal medial'),
('Placa anatómica de tibia distal lateral 4 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 4, NULL, 'tibia distal lateral'),
('Placa anatómica de tibia distal lateral 6 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 6, NULL, 'tibia distal lateral'),
('Placa anatómica de tibia distal lateral 8 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 8, NULL, 'tibia distal lateral'),
('Placa anatómica de tibia distal lateral 10 orificios', 'Grandes Fragmentos', 'Placa anatómica', NULL, 10, NULL, 'tibia distal lateral'),
('Tornillo cortical 4.5mm x 16mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 16, 'cortical'),
('Tornillo cortical 4.5mm x 18mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 18, 'cortical'),
('Tornillo cortical 4.5mm x 20mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 20, 'cortical'),
('Tornillo cortical 4.5mm x 22mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 22, 'cortical'),
('Tornillo cortical 4.5mm x 24mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 24, 'cortical'),
('Tornillo cortical 4.5mm x 26mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 26, 'cortical'),
('Tornillo cortical 4.5mm x 28mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 28, 'cortical'),
('Tornillo cortical 4.5mm x 30mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 30, 'cortical'),
('Tornillo cortical 4.5mm x 32mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 32, 'cortical'),
('Tornillo cortical 4.5mm x 34mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 34, 'cortical'),
('Tornillo cortical 4.5mm x 36mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 36, 'cortical'),
('Tornillo cortical 4.5mm x 38mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 38, 'cortical'),
('Tornillo cortical 4.5mm x 40mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 40, 'cortical'),
('Tornillo cortical 4.5mm x 42mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 42, 'cortical'),
('Tornillo cortical 4.5mm x 44mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 44, 'cortical'),
('Tornillo cortical 4.5mm x 46mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 46, 'cortical'),
('Tornillo cortical 4.5mm x 48mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 48, 'cortical'),
('Tornillo cortical 4.5mm x 50mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 50, 'cortical'),
('Tornillo cortical 4.5mm x 55mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 55, 'cortical'),
('Tornillo cortical 4.5mm x 60mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 60, 'cortical'),
('Tornillo cortical 4.5mm x 65mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 65, 'cortical'),
('Tornillo cortical 4.5mm x 70mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 70, 'cortical'),
('Tornillo cortical 4.5mm x 75mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 75, 'cortical'),
('Tornillo cortical 4.5mm x 80mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 80, 'cortical'),
('Tornillo cortical 4.5mm x 90mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 90, 'cortical'),
('Tornillo cortical 4.5mm x 100mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 100, 'cortical'),
('Tornillo cortical 4.5mm x 110mm', 'Grandes Fragmentos', 'Tornillo', 4.5, NULL, 110, 'cortical'),
('Tornillo esponjoso 6.5mm rosca total x 30mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 30, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 35mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 35, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 40mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 40, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 45mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 45, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 50mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 50, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 55mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 55, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 60mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 60, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 65mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 65, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 70mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 70, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 75mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 75, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 80mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 80, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 85mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 85, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 90mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 90, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 95mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 95, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca total x 100mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 100, 'esponjoso rosca total'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 35mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 35, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 40mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 40, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 45mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 45, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 50mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 50, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 55mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 55, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 60mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 60, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 65mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 65, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 70mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 70, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 75mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 75, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 80mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 80, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 85mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 85, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 90mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 90, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 16mm x 100mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 100, 'esponjoso rosca parcial 16mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 60mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 60, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 65mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 65, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 70mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 70, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 75mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 75, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 80mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 80, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 85mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 85, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 90mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 90, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 95mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 95, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 100mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 100, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 110mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 110, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 120mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 120, 'esponjoso rosca parcial 32mm'),
('Tornillo esponjoso 6.5mm rosca parcial 32mm x 130mm', 'Grandes Fragmentos', 'Tornillo', 6.5, NULL, 130, 'esponjoso rosca parcial 32mm'),
('Tornillo de bloqueo 5.0mm x 18mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 18, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 20mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 20, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 22mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 22, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 24mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 24, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 26mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 26, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 28mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 28, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 30mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 30, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 32mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 32, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 34mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 34, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 36mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 36, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 38mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 38, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 40mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 40, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 42mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 42, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 44mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 44, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 46mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 46, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 48mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 48, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 50mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 50, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 55mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 55, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 60mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 60, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 70mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 70, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 80mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 80, 'bloqueo'),
('Tornillo de bloqueo 5.0mm x 90mm', 'Grandes Fragmentos', 'Tornillo', 5.0, NULL, 90, 'bloqueo'),
('Tornillo cefálico DHS x 75mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 75, 'cefálico DHS'),
('Tornillo cefálico DHS x 80mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 80, 'cefálico DHS'),
('Tornillo cefálico DHS x 85mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 85, 'cefálico DHS'),
('Tornillo cefálico DHS x 90mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 90, 'cefálico DHS'),
('Tornillo cefálico DHS x 95mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 95, 'cefálico DHS'),
('Tornillo cefálico DHS x 100mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 100, 'cefálico DHS'),
('Tornillo cefálico DHS x 105mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 105, 'cefálico DHS'),
('Tornillo cefálico DHS x 110mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 110, 'cefálico DHS'),
('Tornillo cefálico DHS x 115mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 115, 'cefálico DHS'),
('Tornillo cefálico DHS x 120mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 120, 'cefálico DHS'),
('Tornillo cefálico DCS x 75mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 75, 'cefálico DCS'),
('Tornillo cefálico DCS x 80mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 80, 'cefálico DCS'),
('Tornillo cefálico DCS x 85mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 85, 'cefálico DCS'),
('Tornillo cefálico DCS x 90mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 90, 'cefálico DCS'),
('Tornillo cefálico DCS x 95mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 95, 'cefálico DCS'),
('Tornillo cefálico DCS x 100mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 100, 'cefálico DCS'),
('Tornillo cefálico DCS x 105mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 105, 'cefálico DCS'),
('Tornillo cefálico DCS x 110mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 110, 'cefálico DCS'),
('Tornillo cefálico DCS x 115mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 115, 'cefálico DCS'),
('Tornillo cefálico DCS x 120mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 120, 'cefálico DCS'),
('Tornillo de compresión DHS x 38mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 38, 'compresión DHS'),
('Tornillo de compresión DHS x 42mm', 'Grandes Fragmentos', 'Tornillo', NULL, NULL, 42, 'compresión DHS'),
('Tornillo canulado 7.0mm x 50mm', 'Grandes Fragmentos', 'Tornillo', 7.0, NULL, 50, 'canulado'),
('Tornillo canulado 7.0mm x 60mm', 'Grandes Fragmentos', 'Tornillo', 7.0, NULL, 60, 'canulado'),
('Tornillo canulado 7.0mm x 70mm', 'Grandes Fragmentos', 'Tornillo', 7.0, NULL, 70, 'canulado'),
('Tornillo canulado 7.0mm x 80mm', 'Grandes Fragmentos', 'Tornillo', 7.0, NULL, 80, 'canulado'),
('Tornillo canulado 7.0mm x 90mm', 'Grandes Fragmentos', 'Tornillo', 7.0, NULL, 90, 'canulado'),
('Tornillo canulado 7.0mm x 100mm', 'Grandes Fragmentos', 'Tornillo', 7.0, NULL, 100, 'canulado'),
('Tornillo canulado 7.0mm x 110mm', 'Grandes Fragmentos', 'Tornillo', 7.0, NULL, 110, 'canulado'),
('Tornillo canulado 7.0mm x 120mm', 'Grandes Fragmentos', 'Tornillo', 7.0, NULL, 120, 'canulado'),
('Tornillo canulado 7.0mm x 130mm', 'Grandes Fragmentos', 'Tornillo', 7.0, NULL, 130, 'canulado'),
('Arandela 4.5mm', 'Grandes Fragmentos', 'Arandela', 4.5, NULL, NULL, NULL),
('Arandela 6.5mm', 'Grandes Fragmentos', 'Arandela', 6.5, NULL, NULL, NULL),
('Placa DCP 3.5mm 4 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 4, NULL, NULL),
('Placa DCP 3.5mm 5 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 5, NULL, NULL),
('Placa DCP 3.5mm 6 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 6, NULL, NULL),
('Placa DCP 3.5mm 7 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 7, NULL, NULL),
('Placa DCP 3.5mm 8 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 8, NULL, NULL),
('Placa DCP 3.5mm 9 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 9, NULL, NULL),
('Placa DCP 3.5mm 10 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 10, NULL, NULL),
('Placa DCP 3.5mm 12 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 12, NULL, NULL),
('Placa LC-DCP 3.5mm 4 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 4, NULL, NULL),
('Placa LC-DCP 3.5mm 5 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 5, NULL, NULL),
('Placa LC-DCP 3.5mm 6 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 6, NULL, NULL),
('Placa LC-DCP 3.5mm 7 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 7, NULL, NULL),
('Placa LC-DCP 3.5mm 8 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 8, NULL, NULL),
('Placa LC-DCP 3.5mm 9 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 9, NULL, NULL),
('Placa LC-DCP 3.5mm 10 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 10, NULL, NULL),
('Placa LC-DCP 3.5mm 12 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 12, NULL, NULL),
('Placa LCP 3.5mm 4 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 4, NULL, NULL),
('Placa LCP 3.5mm 5 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 5, NULL, NULL),
('Placa LCP 3.5mm 6 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 6, NULL, NULL),
('Placa LCP 3.5mm 7 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 7, NULL, NULL),
('Placa LCP 3.5mm 8 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 8, NULL, NULL),
('Placa LCP 3.5mm 9 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 9, NULL, NULL),
('Placa LCP 3.5mm 10 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 10, NULL, NULL),
('Placa LCP 3.5mm 11 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 11, NULL, NULL),
('Placa LCP 3.5mm 12 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 12, NULL, NULL),
('Placa de reconstrucción 3.5mm 5 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 5, NULL, NULL),
('Placa de reconstrucción 3.5mm 6 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 6, NULL, NULL),
('Placa de reconstrucción 3.5mm 7 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 7, NULL, NULL),
('Placa de reconstrucción 3.5mm 8 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 8, NULL, NULL),
('Placa de reconstrucción 3.5mm 9 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 9, NULL, NULL),
('Placa de reconstrucción 3.5mm 10 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 10, NULL, NULL),
('Placa de reconstrucción 3.5mm 12 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 12, NULL, NULL),
('Placa de reconstrucción 3.5mm 14 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 14, NULL, NULL),
('Placa de reconstrucción 3.5mm bloqueada 5 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 5, NULL, NULL),
('Placa de reconstrucción 3.5mm bloqueada 6 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 6, NULL, NULL),
('Placa de reconstrucción 3.5mm bloqueada 7 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 7, NULL, NULL),
('Placa de reconstrucción 3.5mm bloqueada 8 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 8, NULL, NULL),
('Placa de reconstrucción 3.5mm bloqueada 9 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 9, NULL, NULL),
('Placa de reconstrucción 3.5mm bloqueada 10 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 10, NULL, NULL),
('Placa de reconstrucción 3.5mm bloqueada 12 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 12, NULL, NULL),
('Placa de reconstrucción 3.5mm bloqueada 14 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 14, NULL, NULL),
('Placa tercio de tubo (1/3) 3.5mm 4 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 4, NULL, NULL),
('Placa tercio de tubo (1/3) 3.5mm 5 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 5, NULL, NULL),
('Placa tercio de tubo (1/3) 3.5mm 6 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 6, NULL, NULL),
('Placa tercio de tubo (1/3) 3.5mm 7 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 7, NULL, NULL),
('Placa tercio de tubo (1/3) 3.5mm 8 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 8, NULL, NULL),
('Placa tercio de tubo (1/3) 3.5mm 9 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 9, NULL, NULL),
('Placa tercio de tubo (1/3) 3.5mm 10 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 10, NULL, NULL),
('Placa en T 3.5mm 4 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 4, NULL, NULL),
('Placa en T 3.5mm 5 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 5, NULL, NULL),
('Placa en T 3.5mm 6 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 6, NULL, NULL),
('Placa en T 3.5mm 7 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 7, NULL, NULL),
('Placa en T 3.5mm 8 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 8, NULL, NULL),
('Placa en L 3.5mm 4 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 4, NULL, NULL),
('Placa en L 3.5mm 5 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 5, NULL, NULL),
('Placa en L 3.5mm 6 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 6, NULL, NULL),
('Placa en L 3.5mm 7 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 7, NULL, NULL),
('Placa en L 3.5mm 8 orificios', 'Pequeños Fragmentos', 'Placa', 3.5, 8, NULL, NULL),
('Placa de trébol 3.5mm', 'Pequeños Fragmentos', 'Placa', 3.5, NULL, NULL, 'trébol'),
('Placa anatómica de radio distal volar 5 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 5, NULL, 'radio distal volar'),
('Placa anatómica de radio distal volar 7 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 7, NULL, 'radio distal volar'),
('Placa anatómica de radio distal volar 9 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 9, NULL, 'radio distal volar'),
('Placa anatómica de radio distal dorsal 5 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 5, NULL, 'radio distal dorsal'),
('Placa anatómica de radio distal dorsal 7 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 7, NULL, 'radio distal dorsal'),
('Placa anatómica de clavícula superior 6 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 6, NULL, 'clavícula superior'),
('Placa anatómica de clavícula superior 7 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 7, NULL, 'clavícula superior'),
('Placa anatómica de clavícula superior 8 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 8, NULL, 'clavícula superior'),
('Placa anatómica de clavícula superior 9 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 9, NULL, 'clavícula superior'),
('Placa anatómica de clavícula superior 10 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 10, NULL, 'clavícula superior'),
('Placa anatómica de clavícula con gancho', 'Pequeños Fragmentos', 'Placa anatómica', NULL, NULL, NULL, 'clavícula con gancho'),
('Placa anatómica de peroné distal 4 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 4, NULL, 'peroné distal'),
('Placa anatómica de peroné distal 6 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 6, NULL, 'peroné distal'),
('Placa anatómica de peroné distal 8 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 8, NULL, 'peroné distal'),
('Placa anatómica de peroné distal 10 orificios', 'Pequeños Fragmentos', 'Placa anatómica', NULL, 10, NULL, 'peroné distal'),
('Placa anatómica de calcáneo perfil bajo', 'Pequeños Fragmentos', 'Placa anatómica', NULL, NULL, NULL, 'calcáneo'),
('Placa anatómica de olécranon', 'Pequeños Fragmentos', 'Placa anatómica', NULL, NULL, NULL, 'olécranon'),
('Tornillo cortical 3.5mm x 10mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 10, 'cortical'),
('Tornillo cortical 3.5mm x 12mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 12, 'cortical'),
('Tornillo cortical 3.5mm x 14mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 14, 'cortical'),
('Tornillo cortical 3.5mm x 16mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 16, 'cortical'),
('Tornillo cortical 3.5mm x 18mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 18, 'cortical'),
('Tornillo cortical 3.5mm x 20mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 20, 'cortical'),
('Tornillo cortical 3.5mm x 22mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 22, 'cortical'),
('Tornillo cortical 3.5mm x 24mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 24, 'cortical'),
('Tornillo cortical 3.5mm x 26mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 26, 'cortical'),
('Tornillo cortical 3.5mm x 28mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 28, 'cortical'),
('Tornillo cortical 3.5mm x 30mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 30, 'cortical'),
('Tornillo cortical 3.5mm x 32mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 32, 'cortical'),
('Tornillo cortical 3.5mm x 34mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 34, 'cortical'),
('Tornillo cortical 3.5mm x 36mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 36, 'cortical'),
('Tornillo cortical 3.5mm x 40mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 40, 'cortical'),
('Tornillo cortical 3.5mm x 45mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 45, 'cortical'),
('Tornillo cortical 3.5mm x 50mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 50, 'cortical'),
('Tornillo cortical 3.5mm x 55mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 55, 'cortical'),
('Tornillo cortical 3.5mm x 60mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 60, 'cortical'),
('Tornillo cortical 3.5mm x 65mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 65, 'cortical'),
('Tornillo cortical 3.5mm x 70mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 70, 'cortical'),
('Tornillo esponjoso 4.0mm rosca total x 10mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 10, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 12mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 12, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 14mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 14, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 16mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 16, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 18mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 18, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 20mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 20, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 22mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 22, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 24mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 24, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 26mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 26, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 28mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 28, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 30mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 30, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 32mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 32, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 34mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 34, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 36mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 36, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 40mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 40, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 45mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 45, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca total x 50mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 50, 'esponjoso rosca total'),
('Tornillo esponjoso 4.0mm rosca parcial x 25mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 25, 'esponjoso rosca parcial'),
('Tornillo esponjoso 4.0mm rosca parcial x 30mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 30, 'esponjoso rosca parcial'),
('Tornillo esponjoso 4.0mm rosca parcial x 35mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 35, 'esponjoso rosca parcial'),
('Tornillo esponjoso 4.0mm rosca parcial x 40mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 40, 'esponjoso rosca parcial'),
('Tornillo esponjoso 4.0mm rosca parcial x 45mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 45, 'esponjoso rosca parcial'),
('Tornillo esponjoso 4.0mm rosca parcial x 50mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 50, 'esponjoso rosca parcial'),
('Tornillo de bloqueo 3.5mm x 10mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 10, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 12mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 12, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 14mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 14, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 16mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 16, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 18mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 18, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 20mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 20, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 22mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 22, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 24mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 24, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 26mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 26, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 28mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 28, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 30mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 30, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 32mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 32, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 34mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 34, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 36mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 36, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 40mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 40, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 45mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 45, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 50mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 50, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 55mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 55, 'bloqueo'),
('Tornillo de bloqueo 3.5mm x 60mm', 'Pequeños Fragmentos', 'Tornillo', 3.5, NULL, 60, 'bloqueo'),
('Tornillo maleolar 4.0mm x 30mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 30, 'maleolar'),
('Tornillo maleolar 4.0mm x 35mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 35, 'maleolar'),
('Tornillo maleolar 4.0mm x 40mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 40, 'maleolar'),
('Tornillo maleolar 4.0mm x 45mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 45, 'maleolar'),
('Tornillo maleolar 4.0mm x 50mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 50, 'maleolar'),
('Tornillo maleolar 4.0mm x 55mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 55, 'maleolar'),
('Tornillo maleolar 4.0mm x 60mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 60, 'maleolar'),
('Tornillo maleolar 4.0mm x 65mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 65, 'maleolar'),
('Tornillo maleolar 4.0mm x 70mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 70, 'maleolar'),
('Tornillo canulado 4.0mm x 20mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 20, 'canulado'),
('Tornillo canulado 4.0mm x 25mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 25, 'canulado'),
('Tornillo canulado 4.0mm x 30mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 30, 'canulado'),
('Tornillo canulado 4.0mm x 35mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 35, 'canulado'),
('Tornillo canulado 4.0mm x 40mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 40, 'canulado'),
('Tornillo canulado 4.0mm x 45mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 45, 'canulado'),
('Tornillo canulado 4.0mm x 50mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 50, 'canulado'),
('Tornillo canulado 4.0mm x 55mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 55, 'canulado'),
('Tornillo canulado 4.0mm x 60mm', 'Pequeños Fragmentos', 'Tornillo', 4.0, NULL, 60, 'canulado'),
('Tornillo canulado 4.5mm x 30mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 30, 'canulado'),
('Tornillo canulado 4.5mm x 35mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 35, 'canulado'),
('Tornillo canulado 4.5mm x 40mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 40, 'canulado'),
('Tornillo canulado 4.5mm x 45mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 45, 'canulado'),
('Tornillo canulado 4.5mm x 50mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 50, 'canulado'),
('Tornillo canulado 4.5mm x 55mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 55, 'canulado'),
('Tornillo canulado 4.5mm x 60mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 60, 'canulado'),
('Tornillo canulado 4.5mm x 65mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 65, 'canulado'),
('Tornillo canulado 4.5mm x 70mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 70, 'canulado'),
('Tornillo canulado 4.5mm x 75mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 75, 'canulado'),
('Tornillo canulado 4.5mm x 80mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 80, 'canulado'),
('Tornillo canulado 4.5mm x 90mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 90, 'canulado'),
('Tornillo canulado 4.5mm x 100mm', 'Pequeños Fragmentos', 'Tornillo', 4.5, NULL, 100, 'canulado'),
('Tornillo de Herbert x 16mm', 'Pequeños Fragmentos', 'Tornillo', NULL, NULL, 16, 'Herbert'),
('Tornillo de Herbert x 18mm', 'Pequeños Fragmentos', 'Tornillo', NULL, NULL, 18, 'Herbert'),
('Tornillo de Herbert x 20mm', 'Pequeños Fragmentos', 'Tornillo', NULL, NULL, 20, 'Herbert'),
('Tornillo de Herbert x 22mm', 'Pequeños Fragmentos', 'Tornillo', NULL, NULL, 22, 'Herbert'),
('Tornillo de Herbert x 24mm', 'Pequeños Fragmentos', 'Tornillo', NULL, NULL, 24, 'Herbert'),
('Tornillo de Herbert x 26mm', 'Pequeños Fragmentos', 'Tornillo', NULL, NULL, 26, 'Herbert'),
('Tornillo de Herbert x 28mm', 'Pequeños Fragmentos', 'Tornillo', NULL, NULL, 28, 'Herbert'),
('Tornillo de Schanz 4.0mm rosca corta x 70mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 70, 'rosca corta'),
('Tornillo de Schanz 4.0mm rosca corta x 100mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 100, 'rosca corta'),
('Tornillo de Schanz 4.0mm rosca corta x 125mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 125, 'rosca corta'),
('Tornillo de Schanz 4.0mm rosca corta x 150mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 150, 'rosca corta'),
('Tornillo de Schanz 4.0mm rosca corta x 175mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 175, 'rosca corta'),
('Tornillo de Schanz 4.0mm rosca corta x 200mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 200, 'rosca corta'),
('Tornillo de Schanz 4.0mm rosca larga x 70mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 70, 'rosca larga'),
('Tornillo de Schanz 4.0mm rosca larga x 100mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 100, 'rosca larga'),
('Tornillo de Schanz 4.0mm rosca larga x 125mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 125, 'rosca larga'),
('Tornillo de Schanz 4.0mm rosca larga x 150mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 150, 'rosca larga'),
('Tornillo de Schanz 4.0mm rosca larga x 175mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 175, 'rosca larga'),
('Tornillo de Schanz 4.0mm rosca larga x 200mm', 'Fijación Externa', 'Schanz', 4.0, NULL, 200, 'rosca larga'),
('Tornillo de Schanz 5.0mm rosca corta x 100mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 100, 'rosca corta'),
('Tornillo de Schanz 5.0mm rosca corta x 125mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 125, 'rosca corta'),
('Tornillo de Schanz 5.0mm rosca corta x 150mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 150, 'rosca corta'),
('Tornillo de Schanz 5.0mm rosca corta x 175mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 175, 'rosca corta'),
('Tornillo de Schanz 5.0mm rosca corta x 200mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 200, 'rosca corta'),
('Tornillo de Schanz 5.0mm rosca corta x 225mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 225, 'rosca corta'),
('Tornillo de Schanz 5.0mm rosca corta x 250mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 250, 'rosca corta'),
('Tornillo de Schanz 5.0mm rosca larga x 100mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 100, 'rosca larga'),
('Tornillo de Schanz 5.0mm rosca larga x 125mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 125, 'rosca larga'),
('Tornillo de Schanz 5.0mm rosca larga x 150mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 150, 'rosca larga'),
('Tornillo de Schanz 5.0mm rosca larga x 175mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 175, 'rosca larga'),
('Tornillo de Schanz 5.0mm rosca larga x 200mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 200, 'rosca larga'),
('Tornillo de Schanz 5.0mm rosca larga x 225mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 225, 'rosca larga'),
('Tornillo de Schanz 5.0mm rosca larga x 250mm', 'Fijación Externa', 'Schanz', 5.0, NULL, 250, 'rosca larga'),
('Tornillo de Schanz 6.0mm rosca corta x 125mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 125, 'rosca corta'),
('Tornillo de Schanz 6.0mm rosca corta x 150mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 150, 'rosca corta'),
('Tornillo de Schanz 6.0mm rosca corta x 175mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 175, 'rosca corta'),
('Tornillo de Schanz 6.0mm rosca corta x 200mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 200, 'rosca corta'),
('Tornillo de Schanz 6.0mm rosca corta x 225mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 225, 'rosca corta'),
('Tornillo de Schanz 6.0mm rosca corta x 250mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 250, 'rosca corta'),
('Tornillo de Schanz 6.0mm rosca corta x 275mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 275, 'rosca corta'),
('Tornillo de Schanz 6.0mm rosca larga x 125mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 125, 'rosca larga'),
('Tornillo de Schanz 6.0mm rosca larga x 150mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 150, 'rosca larga'),
('Tornillo de Schanz 6.0mm rosca larga x 175mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 175, 'rosca larga'),
('Tornillo de Schanz 6.0mm rosca larga x 200mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 200, 'rosca larga'),
('Tornillo de Schanz 6.0mm rosca larga x 225mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 225, 'rosca larga'),
('Tornillo de Schanz 6.0mm rosca larga x 250mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 250, 'rosca larga'),
('Tornillo de Schanz 6.0mm rosca larga x 275mm', 'Fijación Externa', 'Schanz', 6.0, NULL, 275, 'rosca larga'),
('Clavo de Steinmann 3.0mm x 200mm', 'Fijación Externa', 'Steinmann', 3.0, NULL, 200, NULL),
('Clavo de Steinmann 3.0mm x 250mm', 'Fijación Externa', 'Steinmann', 3.0, NULL, 250, NULL),
('Clavo de Steinmann 3.0mm x 300mm', 'Fijación Externa', 'Steinmann', 3.0, NULL, 300, NULL),
('Clavo de Steinmann 4.0mm x 200mm', 'Fijación Externa', 'Steinmann', 4.0, NULL, 200, NULL),
('Clavo de Steinmann 4.0mm x 250mm', 'Fijación Externa', 'Steinmann', 4.0, NULL, 250, NULL),
('Clavo de Steinmann 4.0mm x 300mm', 'Fijación Externa', 'Steinmann', 4.0, NULL, 300, NULL),
('Clavo de Steinmann 5.0mm x 200mm', 'Fijación Externa', 'Steinmann', 5.0, NULL, 200, NULL),
('Clavo de Steinmann 5.0mm x 250mm', 'Fijación Externa', 'Steinmann', 5.0, NULL, 250, NULL),
('Clavo de Steinmann 5.0mm x 300mm', 'Fijación Externa', 'Steinmann', 5.0, NULL, 300, NULL),
('Barra de carbono x 100mm', 'Fijación Externa', 'Barra', NULL, NULL, 100, 'carbono'),
('Barra de carbono x 150mm', 'Fijación Externa', 'Barra', NULL, NULL, 150, 'carbono'),
('Barra de carbono x 200mm', 'Fijación Externa', 'Barra', NULL, NULL, 200, 'carbono'),
('Barra de carbono x 250mm', 'Fijación Externa', 'Barra', NULL, NULL, 250, 'carbono'),
('Barra de carbono x 300mm', 'Fijación Externa', 'Barra', NULL, NULL, 300, 'carbono'),
('Barra de carbono x 350mm', 'Fijación Externa', 'Barra', NULL, NULL, 350, 'carbono'),
('Barra de carbono x 400mm', 'Fijación Externa', 'Barra', NULL, NULL, 400, 'carbono'),
('Barra de acero x 100mm', 'Fijación Externa', 'Barra', NULL, NULL, 100, 'acero'),
('Barra de acero x 150mm', 'Fijación Externa', 'Barra', NULL, NULL, 150, 'acero'),
('Barra de acero x 200mm', 'Fijación Externa', 'Barra', NULL, NULL, 200, 'acero'),
('Barra de acero x 250mm', 'Fijación Externa', 'Barra', NULL, NULL, 250, 'acero'),
('Barra de acero x 300mm', 'Fijación Externa', 'Barra', NULL, NULL, 300, 'acero'),
('Barra de acero x 350mm', 'Fijación Externa', 'Barra', NULL, NULL, 350, 'acero'),
('Barra de acero x 400mm', 'Fijación Externa', 'Barra', NULL, NULL, 400, 'acero'),
('Conector barra-barra', 'Fijación Externa', 'Conector', NULL, NULL, NULL, NULL),
('Conector barra-clavo', 'Fijación Externa', 'Conector', NULL, NULL, NULL, NULL),
('Articulación universal', 'Fijación Externa', 'Conector', NULL, NULL, NULL, 'articulación'),
('Mini fijador externo (mano/muñeca)', 'Fijación Externa', 'Mini fijador', NULL, NULL, NULL, NULL),
('Clavo Kirschner 0.8mm x 70mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 0.8, NULL, 70, 'punta lisa'),
('Clavo Kirschner 0.8mm x 100mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 0.8, NULL, 100, 'punta lisa'),
('Clavo Kirschner 0.8mm x 150mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 0.8, NULL, 150, 'punta lisa'),
('Clavo Kirschner 1.0mm x 70mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.0, NULL, 70, 'punta lisa'),
('Clavo Kirschner 1.0mm x 100mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.0, NULL, 100, 'punta lisa'),
('Clavo Kirschner 1.0mm x 150mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.0, NULL, 150, 'punta lisa'),
('Clavo Kirschner 1.2mm x 70mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.2, NULL, 70, 'punta lisa'),
('Clavo Kirschner 1.2mm x 100mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.2, NULL, 100, 'punta lisa'),
('Clavo Kirschner 1.2mm x 150mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.2, NULL, 150, 'punta lisa'),
('Clavo Kirschner 1.2mm x 250mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.2, NULL, 250, 'punta lisa'),
('Clavo Kirschner 1.4mm x 100mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.4, NULL, 100, 'punta lisa'),
('Clavo Kirschner 1.4mm x 150mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.4, NULL, 150, 'punta lisa'),
('Clavo Kirschner 1.4mm x 250mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.4, NULL, 250, 'punta lisa'),
('Clavo Kirschner 1.6mm x 100mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.6, NULL, 100, 'punta lisa'),
('Clavo Kirschner 1.6mm x 150mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.6, NULL, 150, 'punta lisa'),
('Clavo Kirschner 1.6mm x 250mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.6, NULL, 250, 'punta lisa'),
('Clavo Kirschner 1.8mm x 150mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.8, NULL, 150, 'punta lisa'),
('Clavo Kirschner 1.8mm x 250mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 1.8, NULL, 250, 'punta lisa'),
('Clavo Kirschner 2.0mm x 150mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 2.0, NULL, 150, 'punta lisa'),
('Clavo Kirschner 2.0mm x 250mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 2.0, NULL, 250, 'punta lisa'),
('Clavo Kirschner 2.5mm x 150mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 2.5, NULL, 150, 'punta lisa'),
('Clavo Kirschner 2.5mm x 250mm punta lisa', 'Clavos K y Alambre', 'Kirschner', 2.5, NULL, 250, 'punta lisa'),
('Clavo Kirschner 1.0mm x 70mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 1.0, NULL, 70, 'punta roscada'),
('Clavo Kirschner 1.0mm x 100mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 1.0, NULL, 100, 'punta roscada'),
('Clavo Kirschner 1.2mm x 100mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 1.2, NULL, 100, 'punta roscada'),
('Clavo Kirschner 1.2mm x 150mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 1.2, NULL, 150, 'punta roscada'),
('Clavo Kirschner 1.4mm x 150mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 1.4, NULL, 150, 'punta roscada'),
('Clavo Kirschner 1.6mm x 150mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 1.6, NULL, 150, 'punta roscada'),
('Clavo Kirschner 1.6mm x 250mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 1.6, NULL, 250, 'punta roscada'),
('Clavo Kirschner 1.8mm x 150mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 1.8, NULL, 150, 'punta roscada'),
('Clavo Kirschner 2.0mm x 150mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 2.0, NULL, 150, 'punta roscada'),
('Clavo Kirschner 2.0mm x 250mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 2.0, NULL, 250, 'punta roscada'),
('Clavo Kirschner 2.5mm x 250mm punta roscada', 'Clavos K y Alambre', 'Kirschner', 2.5, NULL, 250, 'punta roscada'),
('Alambre de cerclaje calibre 1.0mm (rollo)', 'Clavos K y Alambre', 'Alambre', 1.0, NULL, NULL, 'cerclaje rollo'),
('Alambre de cerclaje calibre 1.25mm (rollo)', 'Clavos K y Alambre', 'Alambre', 1.25, NULL, NULL, 'cerclaje rollo'),
('Alambre de cerclaje calibre 1.5mm (rollo)', 'Clavos K y Alambre', 'Alambre', 1.5, NULL, NULL, 'cerclaje rollo'),
('Alambre quirúrgico para banda de tensión 1.25mm', 'Clavos K y Alambre', 'Alambre', 1.25, NULL, NULL, 'banda de tensión');

COMMIT;
